cache: cargo
dist: trusty

git:
  depth: 1

install: sh scripts/ci/travis/install/x86_64-unknown-linux-cirs.sh
language: rust
rust: nightly
script: sh scripts/x86_64-unknown-linux-cirs.sh
sudo: required
