cache: cargo
dist: trusty

git:
  depth: 1

install:
- cargo install xargo --force
- rustup component add rust-src
language: rust
rust: nightly
script: sh scripts/x86_64-unknown-linux-cirs
sudo: required
